channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.3
  - openssl=1.1.1n
  - pip=21.2.4
  - python=3.9.12
  - readline=8.1.2
  - setuptools=58.0.4
  - sqlite=3.38.2
  - tk=8.6.11
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - black==22.3.0
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - click==8.1.2
    - cycler==0.11.0
    - docstring-parser==0.13
    - faiss-gpu==1.7.2
    - fonttools==4.32.0
    - frozenlist==1.3.0
    - fsspec==2022.3.0
    - google-auth==2.6.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - idna==3.3
    - importlib-metadata==4.11.3
    - joblib==1.1.0
    - jsonargparse==4.5.0
    - kiwisolver==1.4.2
    - markdown==3.3.6
    - matplotlib==3.5.1
    - multidict==6.0.2
    - mypy-extensions==0.4.3
    - numpy==1.22.3
    - oauthlib==3.2.0
    - packaging==21.3
    - pathspec==0.9.0
    - pillow==9.1.0
    - platformdirs==2.5.1
    - protobuf==3.20.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.2
    - pyparsing==3.0.8
    - python-dateutil==2.8.2
    - pytorch-lightning==1.6.0
    - pytorch-metric-learning==1.3.0
    - pyyaml==6.0
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - six==1.16.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tomli==2.0.1
    - torch==1.11.0
    - torchmetrics==0.7.3
    - torchvision==0.12.0
    - tqdm==4.64.0
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - werkzeug==2.1.1
    - yarl==1.7.2
    - zipp==3.8.0
