trainer:
  max_epochs: 20
model:
  class_path: models.ClassificationNet
  init_args:
    embedding_net: models.EmbeddingNet
    n_classes: 10
    loss_func: torch.nn.CrossEntropyLoss
data:
  class_path: data_modules.BaseDataModule
  init_args:
    batch_size: 1000
    num_workers: 0