trainer:
  max_epochs: 1
model:
  class_path: models.MetricNet
  init_args:
    loss_func:
      class_path: my_losses.ContrastiveLoss
      init_args:
        margin: 1
    embedding_net: models.EmbeddingNet

data:
  class_path: data_modules.MetricDataModule
  init_args:
    batch_size: 1000
    metric_name: siamese
    num_workers: 8
    dataset_name: FashionMNIST